// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package repo

import (
	"context"
	"time"
)

const batchDeleteChatMessages = `-- name: BatchDeleteChatMessages :exec
do $$
declare
  rows_deleted int;
begin
  loop
    delete from chat_messages
    where ctid in (
      select ctid
      from chat_messages
      where (case when is_deleted = true then 1 else 0 end) = 1
      limit 1000
    );
    get diagnostics rows_deleted = row_count;
    exit when rows_deleted = 0;
    -- perform pg_sleep(@batch_delay::interval);
  end loop;
end $$
`

func (q *Queries) BatchDeleteChatMessages(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, batchDeleteChatMessages)
	return err
}

const checkChatPartnerID = `-- name: CheckChatPartnerID :one
select exists (
  select 1
  from chat_messages
  where is_deleted = false and
        ((sender_id = $1 and receiver_id = $2) or (sender_id = $2 and receiver_id = $1))
  for update
)
`

type CheckChatPartnerIDParams struct {
	UserID    string
	PartnerID string
}

func (q *Queries) CheckChatPartnerID(ctx context.Context, arg CheckChatPartnerIDParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkChatPartnerID, arg.UserID, arg.PartnerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getAllChatPartnerIDs = `-- name: GetAllChatPartnerIDs :many
select distinct
  (case when sender_id = $1 then receiver_id else sender_id end)::varchar as id
from chat_messages
where is_deleted = false and (sender_id = $1 or receiver_id = $1)
`

func (q *Queries) GetAllChatPartnerIDs(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllChatPartnerIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatMessageByID = `-- name: GetChatMessageByID :one
select sender_id, receiver_id
from chat_messages
where is_deleted = false and id = $1
for update
`

type GetChatMessageByIDRow struct {
	SenderID   string
	ReceiverID string
}

func (q *Queries) GetChatMessageByID(ctx context.Context, id string) (GetChatMessageByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getChatMessageByID, id)
	var i GetChatMessageByIDRow
	err := row.Scan(&i.SenderID, &i.ReceiverID)
	return i, err
}

const getChatMessages = `-- name: GetChatMessages :many
select
  id,
  content,
  sent_at,
  is_read,
  (sender_id = $2) as from_me
from chat_messages 
where is_deleted = false and
      ((sender_id = $2 and receiver_id = $3) or (sender_id = $3 and receiver_id = $2)) and
      ($4::varchar = '' or id < $4::varchar)
order by id desc
limit $1
`

type GetChatMessagesParams struct {
	Limit         int32
	UserID        string
	PartnerID     string
	LastMessageID string
}

type GetChatMessagesRow struct {
	ID      string
	Content string
	SentAt  time.Time
	IsRead  bool
	FromMe  bool
}

func (q *Queries) GetChatMessages(ctx context.Context, arg GetChatMessagesParams) ([]GetChatMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getChatMessages,
		arg.Limit,
		arg.UserID,
		arg.PartnerID,
		arg.LastMessageID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChatMessagesRow{}
	for rows.Next() {
		var i GetChatMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.SentAt,
			&i.IsRead,
			&i.FromMe,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChats = `-- name: GetChats :many
with last_messages as (
  select
    (case when m.sender_id = $3 then m.receiver_id else m.sender_id end)::varchar as partner_id,
    max(m.id)::varchar as last_message_id
  from chat_messages m
  where is_deleted = false and (m.sender_id = $3 or m.receiver_id = $3)
  group by partner_id
)
select
  u.id,
  u.name,
  u.username,
  lm.last_message_id
from last_messages lm
join users u on u.id = lm.partner_id
where ($2::varchar = '' or lm.last_message_id < $2::varchar)
order by lm.last_message_id desc
limit $1
`

type GetChatsParams struct {
	Limit                        int32
	LastMessageIDWithLastPartner string
	UserID                       string
}

type GetChatsRow struct {
	ID            string
	Name          string
	Username      string
	LastMessageID string
}

func (q *Queries) GetChats(ctx context.Context, arg GetChatsParams) ([]GetChatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getChats, arg.Limit, arg.LastMessageIDWithLastPartner, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChatsRow{}
	for rows.Next() {
		var i GetChatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.LastMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadCountsForUser = `-- name: GetUnreadCountsForUser :many
select
  sender_id as partner_id,
  count(*)
from chat_messages
where is_deleted = false and receiver_id = $1 and is_read = false
group by sender_id
`

type GetUnreadCountsForUserRow struct {
	PartnerID string
	Count     int64
}

func (q *Queries) GetUnreadCountsForUser(ctx context.Context, userID string) ([]GetUnreadCountsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getUnreadCountsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnreadCountsForUserRow{}
	for rows.Next() {
		var i GetUnreadCountsForUserRow
		if err := rows.Scan(&i.PartnerID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChatMessage = `-- name: InsertChatMessage :exec
insert into chat_messages (id, sender_id, receiver_id, content, sent_at)
values ($1, $2, $3, $4, $5)
`

type InsertChatMessageParams struct {
	ID         string
	SenderID   string
	ReceiverID string
	Content    string
	SentAt     time.Time
}

func (q *Queries) InsertChatMessage(ctx context.Context, arg InsertChatMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertChatMessage,
		arg.ID,
		arg.SenderID,
		arg.ReceiverID,
		arg.Content,
		arg.SentAt,
	)
	return err
}

const markChatAsDeleted = `-- name: MarkChatAsDeleted :exec
update chat_messages
set is_deleted = true
where ((sender_id = $1 and receiver_id = $2) or (sender_id = $2 and receiver_id = $1))
`

type MarkChatAsDeletedParams struct {
	UserID    string
	PartnerID string
}

func (q *Queries) MarkChatAsDeleted(ctx context.Context, arg MarkChatAsDeletedParams) error {
	_, err := q.db.ExecContext(ctx, markChatAsDeleted, arg.UserID, arg.PartnerID)
	return err
}

const markChatMessageAsDeleted = `-- name: MarkChatMessageAsDeleted :exec
update chat_messages set is_deleted = true where id = $1
`

func (q *Queries) MarkChatMessageAsDeleted(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markChatMessageAsDeleted, id)
	return err
}

const markMessagesAsRead = `-- name: MarkMessagesAsRead :many
update chat_messages 
set is_read = true
where receiver_id = $1 and sender_id = $2 and
      ($3::varchar = '' or id <= $3::varchar) and
      is_read = false
returning id
`

type MarkMessagesAsReadParams struct {
	UserID        string
	PartnerID     string
	UptoMessageID string
}

func (q *Queries) MarkMessagesAsRead(ctx context.Context, arg MarkMessagesAsReadParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, markMessagesAsRead, arg.UserID, arg.PartnerID, arg.UptoMessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
