// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package repo

import (
	"context"
)

const checkClientID = `-- name: CheckClientID :one
select exists (select 1 from clients where id = $1 for update)
`

func (q *Queries) CheckClientID(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkClientID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertClient = `-- name: InsertClient :exec
insert into clients (id, platform, os, app)
values ($1, $2, $3, $4)
`

type InsertClientParams struct {
	ID       string
	Platform string
	Os       string
	App      string
}

func (q *Queries) InsertClient(ctx context.Context, arg InsertClientParams) error {
	_, err := q.db.ExecContext(ctx, insertClient,
		arg.ID,
		arg.Platform,
		arg.Os,
		arg.App,
	)
	return err
}

const updateClient = `-- name: UpdateClient :exec
update clients set app = $1 where id = $2
`

type UpdateClientParams struct {
	App string
	ID  string
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) error {
	_, err := q.db.ExecContext(ctx, updateClient, arg.App, arg.ID)
	return err
}
