// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package repo

import (
	"context"
)

const checkClientID = `-- name: CheckClientID :one
select exists (select 1 from clients where id = $1 for update)
`

func (q *Queries) CheckClientID(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkClientID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertClient = `-- name: InsertClient :exec
insert into clients (id, platform, os)
values ($1, $2, $3)
`

type InsertClientParams struct {
	ID       string
	Platform string
	Os       string
}

func (q *Queries) InsertClient(ctx context.Context, arg InsertClientParams) error {
	_, err := q.db.ExecContext(ctx, insertClient, arg.ID, arg.Platform, arg.Os)
	return err
}
