// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"database/sql"
	"time"
)

type ChatMessage struct {
	ID         string
	SenderID   sql.NullString
	ReceiverID sql.NullString
	Content    string
	SentAt     time.Time
	IsRead     bool
}

type Client struct {
	ID       string
	Platform string
	Os       string
}

type Otp struct {
	ID        string
	UserID    string
	ClientID  string
	OtpHash   string
	Channel   string
	Purpose   string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Session struct {
	ID        string
	Token     string
	CsrfToken string
	UserID    string
	ClientID  string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type User struct {
	ID              string
	Name            string
	Username        string
	Email           string
	EmailIsVerified bool
	Bio             string
	JoinedAt        time.Time
}
