// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: otps.sql

package repo

import (
	"context"
	"time"
)

const batchDeleteExpiredOtps = `-- name: BatchDeleteExpiredOtps :exec
do $$
declare
  rows_deleted integer;
begin
  loop
    delete from otps
    where ctid in (
      select ctid
      from otps
      where expires_at <= now()
      limit 1000
    );
    get diagnostics rows_deleted = row_count;
    exit when rows_deleted = 0;
  end loop;
end $$
`

func (q *Queries) BatchDeleteExpiredOtps(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, batchDeleteExpiredOtps)
	return err
}

const deleteOtp = `-- name: DeleteOtp :exec
delete from otps where id = $1
`

func (q *Queries) DeleteOtp(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteOtp, id)
	return err
}

const getOtpByID = `-- name: GetOtpByID :one
select id, user_id, otp_hash, channel, purpose, created_at, expires_at from otps where id = $1 for update
`

func (q *Queries) GetOtpByID(ctx context.Context, id string) (Otp, error) {
	row := q.db.QueryRowContext(ctx, getOtpByID, id)
	var i Otp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OtpHash,
		&i.Channel,
		&i.Purpose,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertOtp = `-- name: InsertOtp :exec
insert into otps (id, user_id, otp_hash, channel, purpose, expires_at)
values ($1, $2, $3, $4, $5, $6)
`

type InsertOtpParams struct {
	ID        string
	UserID    string
	OtpHash   string
	Channel   string
	Purpose   string
	ExpiresAt time.Time
}

func (q *Queries) InsertOtp(ctx context.Context, arg InsertOtpParams) error {
	_, err := q.db.ExecContext(ctx, insertOtp,
		arg.ID,
		arg.UserID,
		arg.OtpHash,
		arg.Channel,
		arg.Purpose,
		arg.ExpiresAt,
	)
	return err
}
