// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package repo

import (
	"context"
	"time"
)

const batchDeleteExpriredSessions = `-- name: BatchDeleteExpriredSessions :exec
do $$
declare
  rows_deleted integer;
begin
  loop
  delete from sessions
  where ctid in (
    select ctid
    from sessions
    where expires_at <= now()
    limit 1000
  );
  get diagnostics rows_deleted = row_count;
  exit when rows_deleted = 0;
end loop;
end $$
`

func (q *Queries) BatchDeleteExpriredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, batchDeleteExpriredSessions)
	return err
}

const checkCsrfTokenForSession = `-- name: CheckCsrfTokenForSession :one
select exists (select 1 from sessions where id = $2 and csrf_token = $1 for update)
`

type CheckCsrfTokenForSessionParams struct {
	CsrfToken string
	SessionID string
}

func (q *Queries) CheckCsrfTokenForSession(ctx context.Context, arg CheckCsrfTokenForSessionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkCsrfTokenForSession, arg.CsrfToken, arg.SessionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkSessionForUser = `-- name: CheckSessionForUser :one
select exists (select 1 from sessions where id = $1 and user_id = $2 for update)
`

type CheckSessionForUserParams struct {
	ID     string
	UserID string
}

func (q *Queries) CheckSessionForUser(ctx context.Context, arg CheckSessionForUserParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkSessionForUser, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getActiveSessionsForUser = `-- name: GetActiveSessionsForUser :many
select 
  id,
  platform, 
  os
from sessions s
where user_id = $1
`

type GetActiveSessionsForUserRow struct {
	ID       string
	Platform string
	Os       string
}

func (q *Queries) GetActiveSessionsForUser(ctx context.Context, userID string) ([]GetActiveSessionsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveSessionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveSessionsForUserRow{}
	for rows.Next() {
		var i GetActiveSessionsForUserRow
		if err := rows.Scan(&i.ID, &i.Platform, &i.Os); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionById = `-- name: GetSessionById :one
select id, token, csrf_token, user_id, platform, os, created_at, expires_at from sessions where id = $1
`

func (q *Queries) GetSessionById(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionById, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.CsrfToken,
		&i.UserID,
		&i.Platform,
		&i.Os,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
insert into sessions (id, token, csrf_token, user_id, os, platform, expires_at)
values ($1, $2, $3, $4, $5, $6, $7)
`

type InsertSessionParams struct {
	ID        string
	Token     string
	CsrfToken string
	UserID    string
	Os        string
	Platform  string
	ExpiresAt time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession,
		arg.ID,
		arg.Token,
		arg.CsrfToken,
		arg.UserID,
		arg.Os,
		arg.Platform,
		arg.ExpiresAt,
	)
	return err
}

const removeSession = `-- name: RemoveSession :exec
delete from sessions where id = $1
`

func (q *Queries) RemoveSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, removeSession, id)
	return err
}
