// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repo

import (
	"context"
)

const checkEmail = `-- name: CheckEmail :one
select exists (select 1 from users where email = $1 for update)
`

func (q *Queries) CheckEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkUserID = `-- name: CheckUserID :one
select exists (select 1 from users where id = $1 for update)
`

func (q *Queries) CheckUserID(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkUsername = `-- name: CheckUsername :one
select exists (select 1 from users where username = $1 for update)
`

func (q *Queries) CheckUsername(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUsername, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteUser = `-- name: DeleteUser :exec
delete from users where id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, name, username, email, email_is_verified, bio, joined_at from users where email = $1 for update
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailIsVerified,
		&i.Bio,
		&i.JoinedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, name, username, email, email_is_verified, bio, joined_at from users where id = $1 for update
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailIsVerified,
		&i.Bio,
		&i.JoinedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
select id, name, username, email, email_is_verified, bio, joined_at from users where username = $1 for update
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Email,
		&i.EmailIsVerified,
		&i.Bio,
		&i.JoinedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :exec
insert into users (id, name, username, email, bio)
values ($1, $2, $3, $4, $5)
`

type InsertUserParams struct {
	ID       string
	Name     string
	Username string
	Email    string
	Bio      string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser,
		arg.ID,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.Bio,
	)
	return err
}

const markEmailAsVerified = `-- name: MarkEmailAsVerified :exec
update users set email_is_verified = true where id = $1
`

func (q *Queries) MarkEmailAsVerified(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markEmailAsVerified, id)
	return err
}

const searchUsers = `-- name: SearchUsers :many
select id, name, username, email, email_is_verified, bio, joined_at
from users
where (name ilike '%' || $2::varchar || '%' or username ilike '%' || $2::varchar || '%') and 
      ($3::varchar = '' or id < $3::varchar)
order by id desc
limit $1
`

type SearchUsersParams struct {
	Limit  int32
	Query  string
	LastID string
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, searchUsers, arg.Limit, arg.Query, arg.LastID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.Email,
			&i.EmailIsVerified,
			&i.Bio,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
update users set 
    name = $1,
    username = $2,
    email = $3,
    bio = $4
where id = $5
`

type UpdateUserParams struct {
	Name     string
	Username string
	Email    string
	Bio      string
	ID       string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Name,
		arg.Username,
		arg.Email,
		arg.Bio,
		arg.ID,
	)
	return err
}
